### ISSUE TITLE
PWA template don't work

### ISSUE THREAD

**Issue by IgorDePaula** [quasarframework/quasar-template-pwa#13]
### Software version

Quasar: 0.14.6
OS: ubuntu 16.04
Node: 6.3.1
NPM: 3.10.3
Browsers: google chrome 60.0.3112.78 (64 bits)
iOS:
Android:
Any other software related to your bug:

### What did you get as the error?

The service worker dont install on localhost.

### What were you expecting?

The service worker dont install on localhost.

### What steps did you take, to get the error?

Only install the template, run it, and apply the  light house.

The pwa template has any special care? 

![selecao_058](https://user-images.githubusercontent.com/2833993/31736302-1c565dc4-b423-11e7-80b7-8d33650aabe5.png)

**Comment by rstoenescu** [comment]
A PWA needs to be run on a webserver under HTTPS. Build then deploy. The scores are close to 100 when generating the template and running in such environment.

**Comment by IgorDePaula** [comment]
Wait, in localhost is not necessary https.

2017-10-19 11:05 GMT-02:00 Razvan Stoenescu <notifications@github.com>:

**Comment by rstoenescu** [comment]
What I am telling is that the PWA requires https to install and work.

Running quasar dev won't install any web worker as that is soly for developing the UI.
What you need is to build the app then deploy on a https webserver.

Please read about PWAs to understand how they work.

**Comment by IgorDePaula** [comment]
https://developers.google.com/web/fundamentals/primers/service-workers/

During development, you can use service workers through localhost. However,
to deploy it to a site, you will need to have HTTPS installed on the server.

2017-10-19 11:16 GMT-02:00 Razvan Stoenescu <notifications@github.com>:

**Comment by rstoenescu** [comment]
What exactly is the issue you are encountering? Give a full detailed description of what commands you type and what you expect the result to be. Thanks.

**Comment by IgorDePaula** [comment]
I expected the least. start the template and everything provided work. I only run:

quasar init pwa folder
cd folder
npm install
npm run dev

But the service worker not install, and not throw errors. It's like a common template, without the features of pwa.

**Comment by rstoenescu** [comment]
The service worker does NOT install while developing, because you do not need it. It also gets in the way with HMR, just to name one problem. Service worker is only installed on production build. Do a production build, deploy to a server with HTTPS and there you have it.

**Comment by IgorDePaula** [comment]
And as I know the features I put in it work?

2017-10-19 14:42 GMT-02:00 Razvan Stoenescu <notifications@github.com>:

**Comment by rstoenescu** [comment]
Not sure I understand your question. If you are referring to your app working as a pwa when built and deployed, then "yes". Develop it like any regular app and when deployed it becomes PWA.

**Comment by IgorDePaula** [comment]
No, You not understand my question, And as I know the features I put in it
work? I reference to service worker, by example.

2017-10-19 16:03 GMT-02:00 Razvan Stoenescu <notifications@github.com>:
