### ISSUE TITLE
0.15 upgrade - dependency was not found

### ISSUE THREAD

**Issue by metaory** [quasarframework/quasar-template-pwa#16]
### Software version

Quasar: 0.15 git+https://git@github.com/quasarframework/quasar-future.git
OS: ArchLinux
Node: 8.8.0
NPM: 5.4.2
Browsers: Chromium 62.0.3202.75

### What did you get as the error?
`This dependency was not found: * quasar in ./src/main.js`

### What steps did you take, to get the error?
* fresh install of  **quasar-template-pwa** 
* replace quasar-framework version from **^0.14.6** to **git+https://git@github.com/quasarframework/quasar-future.git**
* yarn run dev
* observe dependency was not found error

**Comment by rstoenescu** [comment]
Yes, future v0.15 is not compatible with this template as is. It will be on the official v0.15 release. Sorry for any inconvenience. Trying to squeeze all energy to release v0.15 as soon as possible.

**Comment by MoacirSchmidt** [comment]
Could you please inform what is the compatible template for v0.15 beta? In other words, instead of "import { foo } from 'quasar" what can I use?

**Comment by rstoenescu** [comment]
https://github.com/quasarframework/quasar-starter-kit
--> remember until v0.15 is released anything can change. nothing major, it's 99% finalised, but still.
