### ISSUE TITLE
[request] PWA starter kit compatible with Cordova wrapping.

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar-template-pwa#9]
The ability to also wrap Cordova app on the same source code as the PWA starter kit code.
eg. have 2 separate `index.html` files. 1 for the PWA and 1 for the cordova wrap (without the service workers etc.).

**Comment by rstoenescu** [comment]
Just copy over the src folder from/to a default starter kit and you'll get that.
This will get improved in the future. Don't got time to expand on this at the moment.

**Comment by robsoncombr** [comment]
https://github.com/quasarframework/quasar-framework.org/pull/321
